### ISSUE TITLE
java.util.concurrent.TimeoutException: SQLiteCursor.finalize() timed out after 10 seconds

### ISSUE THREAD

**Issue by yuyanghe** [requery/sqlite-android#21] opened 2016-05-25 03:08 UTC
I use you lib in our project  and receiver crash report like this
java.util.concurrent.TimeoutException: SQLiteCursor.finalize() timed out after 10 seconds

**Comment by npurushe** [comment] 2016-05-25 04:19
Which version are you using?

**Comment by yuyanghe** [comment] 2016-05-25 06:34
3.12   are you fix it in the newest version?    what's reaseon?

**Comment by npurushe** [comment] 2016-05-26 04:36
Having the version can help narrow it down. No changes were really made there, however I would suggest you try to reproduce the problem using the latest version and see if you can collect more information about this issue.

**Comment by npurushe** [comment] 2016-06-08 23:39
Closing for now since not able to reproduce, if you have more details on this please add them.

**Closed by npurushe** 2016-06-08 23:39 UTC
